### ISSUE TITLE
Loading YQL failed 

### ISSUE THREAD

**Issue by myneutrino** [htmlpreview/htmlpreview.github.com#67] opened 2019-01-10 14:57 UTC
`Loading failed for the <script> with source “http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20data.headers%20where%20url%3D%22https%3A%2F%2Fhtmlpreview.github.io%2F%22&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&diagnostics=true&callback=HTMLPreview.loadHTML”.`

[As of Thursday, Jan. 3, 2019, the YQL service at query.yahooapis.com will be retired](https://developer.yahoo.com/yql/?guccounter=1)
How fix this problem?

**Comment by niutech** [comment] 2019-01-10 21:07
Dupe of #66. I have just dropped YQL in the latest version.

**Closed by niutech** 2019-01-10 21:07 UTC
