### ISSUE TITLE
having the "No definition found for Table headers" error

### ISSUE THREAD

**Issue by domotruc** [htmlpreview/htmlpreview.github.com#57] opened 2018-01-11 06:10 UTC
Hi,
Since this morning I get "No definition found for Table headers" rendering that page:
http://htmlpreview.github.io/?https://github.com/domotruc/jMQTT/blob/master/doc/fr_FR/index.html
All pages look affected.
Regards

**Comment by niutech** [comment] 2018-01-11 15:48
This is the YQL issue, duplicate of #54.

**Closed by niutech** 2018-01-11 15:48 UTC
